### ISSUE TITLE
Locale groups won't work

### ISSUE THREAD

**Issue by alvarotrigo** [claudetech/node-static-i18n#23]
Having the following YML file:

```yml
home:
  keywords: ffdasfa

text here: whatever
```

Only `text here` gets translated:

```html
<span data-t>text here</span>
<span data-t>demo.keywords</span>
```

Generating:

```html
<span>whatever</span>
<span>demo.keywords</span>
```
